version: "3.7"
services:
    nginx-proxy:
        container_name: nginxProxyDev

        environment:
            FORCE_COLOR: 1

    letsencrypt:
        container_name: nginxProxyLetsEncryptDev

        environment:
            FORCE_COLOR: 1

    whoami:
        image: jwilder/whoami

        ports:
            - 8000

        environment:
            VIRTUAL_HOST: localtest.me
            VIRTUAL_PORT: 8000