version: "3.7"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:1.3-alpine

        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

        ports:
            - 80:80
            - 443:443

        networks:
            - default
            - nginxproxynet

        restart: always

        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro

    letsencrypt:
        image: nginxproxy/acme-companion:2.2

        depends_on:
            - nginx-proxy

        networks:
            - default
            - nginxproxynet

        environment:
            DEFAULT_EMAIL: ${DEFAULT_EMAIL:?Missing environment variable see readme}

        restart: always

        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:rw
            - acme:/etc/acme.sh
            - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    conf:
        driver: local
    vhost:
        driver: local
    html:
        driver: local
    dhparam:
        driver: local
    certs:
        driver: local
    acme:
        driver: local

networks:
    nginxproxynet:
        name: ${PROXY_NETWORK_NAME-nginxproxynet}
