version: "3.7"
services:
    nginx-proxy:
        container_name: nginxProxyProd

    letsencrypt:
        container_name: nginxProxyLetsEncryptProd

        environment:
            ACMESH_DNS_API_CONFIG: |-
                DNS_API: dns_cf
                CF_Token: ${CF_Token}
                CF_Account_ID: ${CF_Account_ID}
