version: "3.7"
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine-0.7.0

        labels:
            - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

        ports:
            - 80:80
            - 443:443

        networks:
            - default
            - nginxproxynet

        restart: always

        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion:v1.13

        depends_on:
            - nginx-proxy
            - nginxproxynet

        networks:
            - default

        environment:
            DEFAULT_EMAIL: ${DEFAULT_EMAIL:?Missing environment variable see readme}

        restart: always

        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    conf: {}
    vhost: {}
    html: {}
    dhparam: {}
    certs: {}

networks:
    nginxproxynet:
        name: ${PROXY_NETWORK_NAME-nginxproxynet}
