name: Deploy

on:
    workflow_dispatch:
        inputs:
            sha:
                description: "Git SHA to deploy. If empty it takes latest"
            environment:
                description: "Environment to deploy"
                required: true
                default: "production"
                type: choice
                options:
                    - production

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            SHA_TO_DEPLOY: ${{ github.event.inputs.sha || github.sha }}
        steps:
            - name: Deploy ${{ env.SHA_TO_DEPLOY }} to ${{ github.event.inputs.environment }}
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  script_stop: true
                  script: |
                      cd /srv/nginx
                      git checkout ${{ env.SHA_TO_DEPLOY }}
                      docker-compose --env-file ./.env.${{ github.event.inputs.environment }} -f docker-compose.yml -f docker-compose.${{ github.event.inputs.environment }}.yml up -d
